<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-5EVK54D" failures="1" tests="1" name="Default test(failed)(failed)" time="0.13" errors="0" timestamp="2022-12-21T08:02:05 IST">
  <testcase classname="testngdiscussion.FailedTestCaseExecution" name="profile" time="0.017">
    <failure type="java.lang.ArithmeticException">
      <![CDATA[java.lang.ArithmeticException
at testngdiscussion.FailedTestCaseExecution.profile(FailedTestCaseExecution.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- profile -->
  <testcase classname="testngdiscussion.FailedTestCaseExecution" name="home" time="0.0">
    <ignored/>
  </testcase> <!-- home -->
  <testcase classname="testngdiscussion.FailedTestCaseExecution" name="login" time="0.0">
    <ignored/>
  </testcase> <!-- login -->
  <testcase classname="testngdiscussion.FailedTestCaseExecution" name="timeline" time="0.0">
    <ignored/>
  </testcase> <!-- timeline -->
  <testcase classname="testngdiscussion.FailedTestCaseExecution" name="logout" time="0.0">
    <ignored/>
  </testcase> <!-- logout -->
</testsuite> <!-- Default test(failed)(failed) -->
